add support for TrackEvent and Experiment
sajari/sdk-node pull request #49
Opened 2022-03-07 01:53 UTC by jkaho

2022-03-07 01:59 UTC, jonathaningram requested changes

2022-03-07 01:59 UTC, jonathaningram commented on src/generated/api/eventsApi.ts
> +    accountId: string,
Unfortunately this is a major version bump:

> MAJOR version when you make incompatible API changes,

https://semver.org/

That's OK though, this is our reality. We just go to 6.0.0.

2022-03-07 02:00 UTC, jonathaningram commented
We also wrap this (for better or worse) and we did for SendEvent. So if you follow that trail, we should do the same for TrackEvent, though we can probably just put this in collections.ts not events.ts. https://github.com/sajari/sdk-node/blob/master/src/events.ts

2022-03-07 02:22 UTC, jonathaningram commented on src/generated/api/eventsApi.ts
> +    accountId: string,
Ah if we're at v4 now, then yep v5. I thought we were on v5 already but I must have misread.

And yep, if the account ID field is required for an RPC, we should pass accountId as the first argument in those cases. If it's optional, I suppose we're going to need to allow them to pass it another way?

2022-03-07 02:22 UTC, jonathaningram requested changes
commented

2022-03-07 22:53 UTC, jkaho commented
@jonathaningram I assume this doesn't call for a major version bump anymore?

2022-03-08 00:00 UTC, jonathaningram commented
@jkaho unfortunately it's still a breaking change. E.g. the signature for this is now:

```
public async sendEvent(
    sendEventRequest: SendEventRequest,
    accountId?: string,
    options: { headers: { [name: string]: string } } = { headers: {} }
  ): Promise<{ response: http.IncomingMessage; body: object }>
```

Before users could call it like `sendEvent(req, opts)` now they have to call it like `sendEvent(req, undefined, opts)`. Which, incidentally, is not the greatest API design but this is what we get with OpenAPI codegen. Though we do provide wrappers, I believe users can still import the generated things, so we should just major bump it.

2022-03-08 00:00 UTC, jonathaningram requested changes
Commented

2022-03-08 00:17 UTC, jkaho commented
@jonathaningram ah got it, makes sense.

2022-03-09 03:32 UTC, jonathaningram approved these changes

2022-03-09 03:47 UTC, jonathaningram requested changes
Actually let's check this again re Account-Id header.

2022-03-10 00:09 UTC, jonathaningram approved these changes

2022-03-10 00:46 UTC, merged